---
deployment:
  tasks:
    # 1️⃣ Définir le chemin de déploiement (remplace USERNAME par ton vrai user cPanel)
    - export DEPLOYPATH=/home4/communal/public_html/
    # 2️⃣ Aller dans le dossier du dépôt
    - cd $DEPLOYPATH

    # 3️⃣ Installer les dépendances PHP
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # 4️⃣ Installer les dépendances JS et builder le front
    - /bin/npm install
    - /bin/npm run build

    # 5️⃣ Copier les fichiers Laravel nécessaires dans public_html
    - /bin/cp -R public/* $DEPLOYPATH

    # 6️⃣ Créer le fichier .env s'il n'existe pas déjà
    - if [ ! -f $DEPLOYPATH/.env ]; then cp .env.example $DEPLOYPATH/.env; fi

    # 7️⃣ Lancer les migrations et seed
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan db:seed --force

    # 8️⃣ Optimiser Laravel
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
