deployment:
  tasks:
    - export PROJECTPATH=/home4/communal/communal_backend
    - export DEPLOYPATH=/home4/communal/public_html

    # Aller dans la racine du projet Laravel
    - cd $PROJECTPATH

    # Installer dépendances PHP
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # Installer dépendances JS et builder le front
    - /bin/npm install
    - /bin/npm run build

    # Copier le contenu du dossier public vers public_html (web)
    - /bin/cp -R public/* $DEPLOYPATH

    # Gestion du fichier .env (création si absent, et modifs)
    - |
      if [ ! -f $PROJECTPATH/.env ]; then
        cp $PROJECTPATH/.env.example $PROJECTPATH/.env
      fi

      set_env_var() {
        local key="$1"
        local value="$2"
        if grep -q "^$key=" "$PROJECTPATH/.env"; then
          sed -i "s|^$key=.*|$key=$value|" "$PROJECTPATH/.env"
        else
          echo "$key=$value" >> "$PROJECTPATH/.env"
        fi
      }

      set_env_var "APP_ENV" "production"
      set_env_var "APP_DEBUG" "false"
      set_env_var "APP_URL" "https://mon-domaine.com"

    # Lancer les migrations et seed
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan db:seed --force

    # Optimiser Laravel
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
